version: '3.8'
services:
  oai-spgwu-tiny:
    image: ${IMAGE_NAME:-oaisoftwarealliance/trf-gen-cn5g:latest}
    container_name: "oai-trf-gen"
    hostname: "oai-trf-gen"
    entrypoint: /bin/bash -c \
      "ip route add 12.1.0.0/16 via ${UPF_IPV4_ADDRESS} dev eth0; sleep infinity"
    ports:
      - "8085:8085/udp"
      - "2152:2152/udp"
      - "80:80"
      - "8080:8080"
    healthcheck:
      test: /bin/bash -c "ip r | grep 12.1.0"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./hosts:/etc/hosts
    environment:
      - TZ=${TZ:-Europe/Berlin}
#    depends_on:
#      - oai-spgwu-tiny
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    cap_drop:
      - ALL
    privileged: true
