version: '3.8'

services:
  mysql:
    image: ${IMAGE_NAME:-mysql:8.0}
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./hosts:/etc/hosts
      - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
      - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
      - /mysql/data:/var/lib/mysql
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-oai_db}
      - MYSQL_USER=${MYSQL_USER:-test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-linux}
    healthcheck:
      test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
      interval: 10s
      timeout: 5s
      retries: 5
