version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
      - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-oai_db}
      - MYSQL_USER=${MYSQL_USER:-test}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-linux}
    healthcheck:
      test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
      interval: 10s
      timeout: 5s
      retries: 5
#    networks:
#      public_net:
#        ipv4_address: 192.168.70.131
