version: '3.8'

services:
    oai_spgwu:
        image: kukkalli/oai-spgwu-tiny:v1.2.0
        privileged: true
        container_name: oai-spgwu-tiny
        hostname: "${SPGW_U_HOSTNAME}"
        ports:
            - "${FABRIC_IP}:2152:2152/udp"
            - "${FABRIC_IP}:8805:8805/udp"
        networks:
            public_net:
                ipv4_address: 192.168.68.133
        environment:
            TZ: "${TZ}"
            PID_DIRECTORY: /var/run
            INSTANCE: "${INSTANCE}"
            SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP: eth0
            PGW_INTERFACE_NAME_FOR_SGI: eth0
            SGW_INTERFACE_NAME_FOR_SX: eth0
            SPGWC0_IP_ADDRESS: "${SGWC_IP_ADDRESS}"
            NETWORK_UE_IP: "${NETWORK_UE_IP}"
            NETWORK_UE_NAT_OPTION: 'yes'
            MCC: "${MCC}"
            MNC: "${MNC}"
            MNC03: '001'
            TAC: 1
            GW_ID: "${GW_ID}"
            REALM: "${REALM}"
        healthcheck:
            test: /bin/bash -c "pgrep oai_spgwu"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: oai-public-net
        ipam:
            config:
                - subnet: 192.168.68.128/26
