#!/bin/sh

# shellcheck disable=SC2046
# shellcheck disable=SC2039
source $(pwd)/env_var
. $(pwd)/env_var

set -e
echo "Waiting for NRF to launch on 8080..."

while ! nc -z "${NRF_IPV4_ADDRESS}" 8080; do
  echo "NRF at IP ${NRF_IPV4_ADDRESS} not connected"
  sleep 0.1 # wait for 1/10 of the second before check again
done

echo "NRF launched"


set -e
echo "Waiting for UDR to launch on 8080..."

while ! nc -z "${UDR_IPV4_ADDRESS}" 3306; do
  echo "UDR at IP ${UDR_IPV4_ADDRESS} not connected"
  sleep 0.1 # wait for 1/10 of the second before check again
done

echo "UDR launched"

