#!/bin/bash

# Source the environment variables
# shellcheck disable=SC2046
source $(pwd)/env_var

# Turn off any running docker compose
docker compose down

# remove existing files
sudo rm -f startup.log
sudo rm -f config.yaml

# Display the env_var file
cat env_var >> startup.log

# shellcheck disable=SC2035
# shellcheck disable=SC2046
sudo chown ubuntu:ubuntu $(pwd)/*

# Pull the docker image
docker pull "${IMAGE_NAME}"

./wait_for_dependencies

docker compose up -d

exit
