#!/bin/bash

# Source the environment variables
source env_var_bkp

# Turn off any running docker compose
docker compose down

# remove existing files
sudo rm -f /home/ubuntu/startup.log
sudo rm -f /home/ubuntu/users.conf
# shellcheck disable=SC2046
sudo mv users.conf users.bkp.$(date '+%Y%m%d')

cat > users.conf << EOF
[${UE_ID_01}]
fullname = ${UE_USER_01_FULLNAME}
hassip = yes
context = users
host = dynamic
transport = udp

[${UE_ID_02}]
fullname = ${UE_USER_02_FULLNAME}
hassip = yes
context = users
host = dynamic
transport = udp
EOF

# Pull the docker image
docker pull "${IMAGE_NAME}"

docker compose up -d


exit
