version: '3.8'

services:
  ims:
    image: ${IMAGE_NAME:-kukkalli/asterisk-ims:1.0.0}
    container_name: "asterisk-ims"
    hostname: "asterisk-ims"
    cap_add:
      - SYS_PTRACE                                          # Only here to help testing
      - NET_ADMIN                                           # Allow NFT, used by AutoBan
      - NET_RAW                                             # Allow NFT, used by AutoBan
    ports:
      - "${SMS_PORT:-80}:${WEBSMSD_PORT:-80}"               # WEBSMSD port mapping
      - "5060:5060/udp"                                     # SIP UDP port
      - "5060:5060"                                         # SIP TCP port
      - "5061:5061"                                         # SIP TLS port
      - "10000-10010:10000-10010/udp"                       # RTP ports
    volumes:
      - ./hosts:/etc/hosts
      - ./sip.conf:/etc/asterisk/sip.conf
      - ./users.conf:/etc/asterisk/users.conf
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL:-4}                     # Logging
      - HOSTNAME=${TELE_SRV:-oai}.${DOMAIN:-tu-chemnitz.de}
      - PULSE_SERVER=unix:/run/pulse/socket                 # Use host audio
      - PULSE_COOKIE=/run/pulse/cookie                      # Use host audio
      - WEBSMSD_PORT=${WEBSMSD_PORT:-80}                    # WEBSMSD internal port
    healthcheck:
      test: /bin/bash -c "pgrep asterisk"
      interval: 10s
      timeout: 5s
      retries: 5
