#!/bin/sh

# shellcheck disable=SC2046
# shellcheck disable=SC2039
source $(pwd)/env_var
. $(pwd)/env_var

set -e
echo "Waiting for NRF to launch on 8080..."

while ! nc -z "${NRF_IPV4_ADDRESS}" 8080; do
  echo "NRF at IP ${NRF_IPV4_ADDRESS} not connected"
  sleep 0.1 # wait for 1/10 of the second before check again
done

echo "NRF launched"

set -e
echo "Waiting for SMF to launch on 80..."

while ! nc -z "${SMF_IPV4_ADDRESS}" 80; do
  echo "AMF at IP ${SMF_IPV4_ADDRESS} not connected"
  sleep 0.1 # wait for 1/10 of the second before check again
done

echo "SMF launched"