#!/bin/sh

# shellcheck disable=SC2046
# shellcheck disable=SC2039
source $(pwd)/env_var
. $(pwd)/env_var

set -e
echo "Waiting for UPF to launch on 80..."

while ! nc -z "${UPF_IPV4_ADDRESS}" 80; do
  echo "UPF at IP ${UPF_IPV4_ADDRESS} not connected"
  sleep 0.1 # wait for 1/10 of the second before check again
done

echo "UPF launched"