version: '3.8'

services:
    cassandra:
        image: cassandra:2.1
        container_name: cassandra-db
        hostname: cassandra-db
        ports:
            - "7000:7000"
            - "7001:7001"
            - "7199:7199"
            - "9042:9042"
            - "9160:9160"
        networks:
            public_net:
                ipv4_address: 192.168.68.130
        environment:
            CASSANDRA_CLUSTER_NAME: "OAI HSS Cluster"
            CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        healthcheck:
            test: /bin/bash -c "nodetool status"
            interval: 10s
            timeout: 5s
            retries: 5

    cassandra_web:
        image: delermando/docker-cassandra-web:v0.4.0
        container_name: cassandra-web
        hostname: cassandra-web
        depends_on: [cassandra]
        ports:
            - "${MANAGEMENT_IP}:3000:3000"
        networks:
            public_net:
                ipv4_address: 192.168.68.131
        environment:
            CASSANDRA_HOST_IP: 192.168.68.130
            CASSANDRA_PORT: 9042

    db_init:
        image: cassandra:2.1
        container_name: db-init
        hostname: db-init
        depends_on: [cassandra]
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 10
        networks:
            public_net:
                ipv4_address: 192.168.68.132
        volumes:
            - ./oai_db.cql:/home/oai_db.cql
        entrypoint: /bin/bash -c "cqlsh --file /home/oai_db.cql 192.168.68.130 && echo 'OK'"

    oai_hss:
        image: kukkalli/oai-hss:v1.2.0
        container_name: oai-hss
        hostname: "${HSS_HOSTNAME}"
        privileged: true
        depends_on: [cassandra]
        ports:
            - "${FABRIC_IP}:3868:3868"
            - "${FABRIC_IP}:5868:5868/tcp"
            - "${FABRIC_IP}:9042:9042/tcp"
            - "${FABRIC_IP}:9080:9080/tcp"
            - "${FABRIC_IP}:9081:9081/tcp"
            - "${FABRIC_IP}:9082:9082"
            - "${FABRIC_IP}:30868:30868"
            - "${FABRIC_IP}:31868:31868"
            - "${FABRIC_IP}:36412:36412/sctp"
        networks:
            public_net:
                ipv4_address: 192.168.68.133
        environment:
            TZ: Europe/Paris
            REALM: "${REALM}"
            HSS_FQDN: "${HSS_FQDN}"
            PREFIX: /openair-hss/etc
            cassandra_Server_IP: 192.168.68.130
            OP_KEY: "${OP_KEY}"
            LTE_K: "${LTE_K}"
            APN1: "${APN1}"
            APN2: "${APN2}"
            FIRST_IMSI: ${FIRST_IMSI}
            NB_USERS: 30
        healthcheck:
            test: /bin/bash -c "pgrep oai_hss"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: oai-public-net
        ipam:
            config:
                - subnet: 192.168.68.128/26
