version: '3.8'

services:
    redis:
        image: redis:6.0.5
        container_name: demo-redis
        privileged: true
        ports:
            - "6380:6380"
        networks:
            public_net:
                ipv4_address: 192.168.68.148
        volumes:
            - ./redis_extern.conf:/usr/local/etc/redis/redis.conf
        entrypoint: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
        healthcheck:
            test: /bin/bash -c "redis-cli -h 192.168.61.148 -p 6380 ping"
            interval: 10s
            timeout: 5s
            retries: 5

    magma_mme:
        image: kukkalli/magma-mme:1.0.0
        container_name: demo-magma-mme
        hostname: mme
        privileged: true
        depends_on: [redis]
        networks:
            public_net:
                ipv4_address: 192.168.68.149
        environment:
            TZ: Europe/Paris
            REALM: openairinterface.org
            PREFIX: /openair-mme/etc
            HSS_HOSTNAME: hss
            HSS_FQDN: hss.openairinterface.org
            HSS_REALM: openairinterface.org
            MME_FQDN: mme.openairinterface.org
            FEATURES: mme_oai
        volumes:
            - ./mme_fd.sprint.conf:/magma-mme/etc/mme_fd.conf.tmplt
            - ./mme.conf:/magma-mme/etc/mme.conf
            - ./mme-cfg.sh:/magma-mme/scripts/mme-cfg.sh
            - ./wait-for-hss.sh
        entrypoint: /bin/bash -c "cd /magma-mme/scripts; ./mme-cfg.sh"
        command: ["./wait-for-it.sh", "$HSS_IP", "--", "python", "app.py"]
        healthcheck:
            test: /bin/bash -c "pgrep oai_mme"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: oai-public-net
        ipam:
            config:
                - subnet: 192.168.68.128/26
