version: '3.8'

services:
  oai-udr:
    container_name: "oai-udr"
    image: ${IMAGE_NAME:-oaisoftwarealliance/oai-udr:v1.5.1}
    volumes:
      - ./hosts:/etc/hosts
      - ./config.yaml:/openair-udr/etc/config.yaml
    environment:
      - TZ=Europe/Paris
      - UDR_NAME=OAI_UDR
      - UDR_INTERFACE_NAME_FOR_NUDR=eth0
      - MYSQL_IPV4_ADDRESS=${MYSQL_IP:-mysql}
      - MYSQL_USER=${MYSQL_USER:-oai_tuc}
      - MYSQL_PASS=${MYSQL_PASSWORD:-oai_tuc}
      - MYSQL_DB=${MYSQL_DATABASE:-oai_db}
      - WAIT_MYSQL=120
      - USE_FQDN_DNS=yes
      - REGISTER_NRF=yes
      - NRF_IPV4_ADDRESS=${NRF_IPV4_ADDRESS}
      - NRF_FQDN=${NRF_FQDN}
#    depends_on:
#      - mysql
#      - oai-nrf
    networks:
      public_net:
          ipv4_address: 192.168.70.136
