version: '3.8'

services:
  oai-udr:
    image: ${IMAGE_NAME:-oaisoftwarealliance/oai-udr:v1.5.1}
    container_name: "oai-udr"
    hostname: "oai-udr"
    ports:
      - "80:80"
      - "8080:8080"
      - "38412:38412/sctp"
    volumes:
      - ./hosts:/etc/hosts
      - ./config.yaml:/openair-udr/etc/config.yaml
    environment:
      - TZ=Europe/Paris
      - UDR_NAME=OAI_UDR
      - UDR_INTERFACE_NAME_FOR_NUDR=eth0
      - MYSQL_IPV4_ADDRESS=${MYSQL_IPV4_ADDRESS:-mysql}
      - MYSQL_USER=${MYSQL_USER:-oai_tuc}
      - MYSQL_PASS=${MYSQL_PASSWORD:-oai_tuc}
      - MYSQL_DB=${MYSQL_DB:-oai_db}
      - WAIT_MYSQL=120
      - USE_FQDN_DNS=yes
      - REGISTER_NRF=yes
      - NRF_IPV4_ADDRESS=${NRF_IPV4_ADDRESS}
      - NRF_FQDN=${NRF_FQDN}
