#!/bin/sh

. env_var

set -e
echo "Waiting for MySQL at IP: ${MYSQL_IPV4_ADDRESS} to launch on 3306..."
# MYSQL_IP="$1"

while ! nc -z "${MYSQL_IPV4_ADDRESS}" 3306; do
  echo "MYSQL at IP ${MYSQL_IPV4_ADDRESS} not connected"
  sleep 0.1 # wait for 1/10 of the second before check again
done

echo "MYSQL launched"

set -e
echo "Waiting for NRF at IP: ${NRF_IPV4_ADDRESS} to launch on 8080..."
# NRF_IP="$2"

while ! nc -z "${NRF_IPV4_ADDRESS}" 8080; do
  echo "NRF at IP ${NRF_IPV4_ADDRESS} not connected"
  sleep 0.1 # wait for 1/10 of the second before check again
done

echo "NRF launched"
