#!/bin/bash

# Source the environment variables
# shellcheck disable=SC2046
source $(pwd)/env_var

# Turn off any running docker compose
docker compose down

# remove existing files
sudo rm -f startup.log
sudo rm -f config.yaml

# Display the env_var file
cat env_var >> startup.log

# shellcheck disable=SC2129
cat > $(pwd)/amf.conf << EOF
################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the OAI Public License, Version 1.1  (the "License"); you may not use this file
# except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.openairinterface.org/?page_id=698
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################

#### This file is a jinja2 template all the values between double curly brace will be replaced with environment variables

AMF =
{
  INSTANCE_ID = 0 ;            # 0 is the default
  PID_DIRECTORY = "/var/run";   # /var/run is the default

  AMF_NAME = "${AMF_NAME}";
  LOG_LEVEL = "${LOG_LEVEL}";

  RELATIVE_CAPACITY = 30;
  # Display statistics about whole system (in seconds)
  STATISTICS_TIMER_INTERVAL = 20;

  CORE_CONFIGURATION:
  {
    EMERGENCY_SUPPORT = "false";
  };

  GUAMI:
  {
    MCC = "${MCC_01}"; MNC = "${MNC_01}"; RegionID = "${AMF_REGION_ID_01}"; AMFSetID = "${AMF_SET_ID_01}"; AMFPointer = "${AMF_POINTER_01}"
  }

  SERVED_GUAMI_LIST = (
    {MCC = "${MCC_01}"; MNC = "${MNC_01}"; RegionID = "${AMF_REGION_ID_01}"; AMFSetID = "${AMF_SET_ID_01}"; AMFPointer = "${AMF_POINTER_01}"}
    #48bits <MCC><MNC><RegionID><AMFSetID><AMFPointer>
  );

  PLMN_SUPPORT_LIST = ({
    MCC = "${PLMN_SL_MCC}"; MNC = "${PLMN_SL_MNC}"; TAC = ${PLMN_SL_TAC};
    SLICE_SUPPORT_LIST = (
      {SST = ${NSSAI_SST_01}; SD = "0xFFFFFF"}
     )
  });

  INTERFACES:
  {
    # AMF binded interface for N1/N2 interface (NGAP)
    NGAP_AMF:
    {
      INTERFACE_NAME = "${AMF_INTERFACE_NAME_FOR_NGAP}";
      IPV4_ADDRESS   = "read";
      PORT           = ${AMF_PORT_NGAP};
      PPID           = 60;
    };

    # AMF binded interface for SBI (N11 (SMF)/N12 (AUSF), etc.)
    SBI:
    {
      INTERFACE_NAME = "${AMF_INTERFACE_NAME_FOR_SBI}";
      IPV4_ADDRESS   = "read";
      # default is 80
      PORT           = ${AMF_PORT_SBI};
      # default is v1
      API_VERSION    = "${AMF_API_VERSION_SBI}";
      # default is 8080
      HTTP2_PORT     = ${AMF_HTTP2_PORT_SBI};

      SMF_INSTANCES_POOL = (
        {SMF_INSTANCE_ID = ${SMF_01_INSTANCE_ID}; IPV4_ADDRESS = "${SMF_01_IPV4_ADDRESS}"; PORT = "${SMF_01_PORT}"; HTTP2_PORT = ${SMF_01_HTTP2_PORT}, VERSION = "${SMF_01_VERSION}"; FQDN = "${SMF_01_FQDN}", SELECTED = "${SMF_01_SELECTED}"}
      );
    };

    NRF :
    {
      IPV4_ADDRESS = "${NRF_IPV4_ADDRESS}";
      PORT         = ${NRF_PORT};            # Default: 80
      API_VERSION  = "${NRF_API_VERSION}";
      FQDN         = "${NRF_FQDN}"
    };

    AUSF :
    {
      IPV4_ADDRESS = "${AUSF_IPV4_ADDRESS}";
      PORT         = ${AUSF_PORT};            # Default: 80
      API_VERSION  = "${AUSF_API_VERSION}";
      FQDN         = "${AUSF_FQDN}"
    };

    UDM :
    {
      IPV4_ADDRESS = "${UDM_IPV4_ADDRESS}";
      PORT         = ${UDM_PORT};    # Default: 80
      API_VERSION  = "${UDM_API_VERSION}";
      FQDN         = "${UDM_FQDN}"
    };

    NSSF :
    {
      IPV4_ADDRESS = "0.0.0.0";
      PORT         = 80;            # Default: 80
      API_VERSION  = "v2";
      FQDN         = "oai-nssf"
    };

  };

  SUPPORT_FEATURES:
  {
     # STRING, {"yes", "no"},
     NF_REGISTRATION = "yes";  # Set to yes if AMF registers to an NRF
     NRF_SELECTION   = "no";    # Set to yes to enable NRF discovery and selection
     EXTERNAL_NRF    = "no";     # Set to yes if AMF works with an external NRF
     SMF_SELECTION   = "no";    # Set to yes to enable SMF discovery and selection
     EXTERNAL_AUSF   = "yes";    # Set to yes if AMF works with an external AUSF
     EXTERNAL_UDM    = "no";     # Set to yes if AMF works with an external UDM
     EXTERNAL_NSSF   = "no";    # Set to yes if AMF works with an external NSSF
     USE_FQDN_DNS    = "yes";   # Set to yes if AMF relies on a DNS to resolve NRF/SMF/UDM/AUSF's FQDN
     USE_HTTP2       = "no";        # Set to yes to enable HTTP2 for AMF server
  }

  AUTHENTICATION:
  {
    ## MySQL mandatory options
    MYSQL_server = "${MYSQL_SERVER}"; # MySQL Server address
    MYSQL_user   = "${MYSQL_USER}";   # Database server login
    MYSQL_pass   = "${MYSQL_PASS}";   # Database server password
    MYSQL_db     = "${MYSQL_DB}";     # Your database name
    RANDOM = "true";
  };

  NAS:
  {
    ORDERED_SUPPORTED_INTEGRITY_ALGORITHM_LIST = ["NIA1" , "NIA2"] ;
    ORDERED_SUPPORTED_CIPHERING_ALGORITHM_LIST = ["NEA0" , "NEA1" , "NEA2"] ;
  };
};
EOF

# shellcheck disable=SC2035
# shellcheck disable=SC2046
sudo chown ubuntu:ubuntu $(pwd)/*

# Pull the docker image
docker pull "${IMAGE_NAME}"

./wait_for_dependencies

docker compose up -d

exit
